package application.Controller;

import javafx.fxml.FXML;
import javafx.scene.control.PasswordField;
import javafx.event.ActionEvent;

public class AuthentificationController {

	// Event Listener on Button.onAction
	@FXML private PasswordField pass ;
	
	@FXML
	public void On_Sumit(ActionEvent event) {
		// TODO Autogenerated
		String x= pass.getText() ;
		
	}
	
}
